### ISSUE TITLE
Nginx

### ISSUE THREAD

**Issue by Asethon** [anilibria/docs#2]
@poiuty , правильно ли я понимаю, что роутинг у вас реализован на стороне сервиса nginx(через lua-script)?
Я включил часть вашего конфига в конфиг nginx для докера, но убрал установку сертификата и обработку lua-скриптов, так как считаю это превышением ответственности со стороны nginx-а.
Судя по https://github.com/anilibria/anilibria/issues/47#issuecomment-465768025, роутинг планируется реализовать на стороне PHP.

Вопрос следующий: насколько, в данный момент, критично для сайта отсутствие lua-скриптов?

**Comment by S-anasol** [comment]
> роутинг у вас реализован на стороне сервиса nginx
Весь роутинг: https://github.com/anilibria/docs/blob/master/install/conf/default#L62-L63

> Вопрос следующий: насколько, в данный момент, критично для сайта отсутствие lua-скриптов?
Там только один луа скрипт и он отвечает за защиту от флуда запросами к сайту или коду никак не относится.
