### ISSUE TITLE
New host for v3 images

### ISSUE THREAD

**Issue by andrian-kars** [anilibria/docs#24]
In the v3 documentation, I see an example for videos:
https://cache.libria.fun/videos/media/ts/9284/3/720/4cc228b26307888f9cb0091ff233a6e3.m3u8

I used https://cache.libria.fun with the preview response from v3 API, but no luck in getting the images:

![image](https://user-images.githubusercontent.com/66482484/211151889-3f263709-8f14-4439-b2ad-883e273b2ddc.png)

![image](https://user-images.githubusercontent.com/66482484/211151756-24b23324-d563-442f-8886-cf5a7c604aca.png)

**Comment by andrian-kars** [comment]
https://anilibria.tv/

**Comment by Glomis** [comment]
Why do not load images from the host https://anilibria.tv/ Only with VPN
