### ISSUE TITLE
title -> posters

### ISSUE THREAD

**Issue by w01f-o** [anilibria/docs#39]
https://anilibria.tv/storage/releases/posters/8499/fs76tpVl8IRylM9n__bfa081957219da1ec0da0646a80aed20.jpg

Картинки загружаются только с включённым VPN

**Comment by Damego** [comment]
Домен https://anilibria.tv заблокирован на территории РФ, поэтому картинки и не грузятся без ВПНа. Используй другие доступные домены, например https://vk.anilib.top
